# Generated by Django 5.1.1 on 2024-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(help_text='Description détaillée du produit (vous pouvez utiliser des retours à la ligne et des puces)'),
        ),
    ]
