# Generated by Django 5.1.1 on 2024-09-14 13:13

# import ckeditor.fields
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
    ]
